// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3T1CB9iK0lmqp-0fqUZcldWzg5IewXEw',
    appId: '1:587921204196:web:600ecf402635f5c4855df1',
    messagingSenderId: '587921204196',
    projectId: 'dars66-32812',
    authDomain: 'dars66-32812.firebaseapp.com',
    storageBucket: 'dars66-32812.appspot.com',
    measurementId: 'G-GG6CS2RDCJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCscm7As9wwWeynrocUK7Pw_UE45Rtzraw',
    appId: '1:587921204196:android:002358e7f426e8d0855df1',
    messagingSenderId: '587921204196',
    projectId: 'dars66-32812',
    storageBucket: 'dars66-32812.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvvoPxd-QzlDqx_QPNv1skIDPTYIRMGL4',
    appId: '1:587921204196:ios:4b6807265af7a75c855df1',
    messagingSenderId: '587921204196',
    projectId: 'dars66-32812',
    storageBucket: 'dars66-32812.appspot.com',
    iosBundleId: 'com.example.cardApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvvoPxd-QzlDqx_QPNv1skIDPTYIRMGL4',
    appId: '1:587921204196:ios:4b6807265af7a75c855df1',
    messagingSenderId: '587921204196',
    projectId: 'dars66-32812',
    storageBucket: 'dars66-32812.appspot.com',
    iosBundleId: 'com.example.cardApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3T1CB9iK0lmqp-0fqUZcldWzg5IewXEw',
    appId: '1:587921204196:web:06458229a12e711b855df1',
    messagingSenderId: '587921204196',
    projectId: 'dars66-32812',
    authDomain: 'dars66-32812.firebaseapp.com',
    storageBucket: 'dars66-32812.appspot.com',
    measurementId: 'G-FT0ZQLDXC1',
  );
}
